@startuml
title Twitter - System Context

top to bottom direction

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

Enterprise_Boundary(enterprise, "Project") {
  System(Iris, "Iris", "", $tags="")
}

Boundary(group_1, "Cloud") {
  System_Ext(Twitter, "Twitter", "The Twitter Platform", $tags="")
}

Person_Ext(TwitterUser, "Twitter User", "A user of the Twitter platform", $tags="")

Rel_D(Twitter, Iris, "Receives data stream", $tags="")
Rel_D(TwitterUser, Twitter, "Tweets", "A Tweet is added to the platform", $tags="")

SHOW_LEGEND()
@enduml
