@startuml
title iamcal/emoji-data - Containers

top to bottom direction

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

System(Iris, "Iris", "", $tags="")

System_Boundary("iamcalemojidata_boundary", "iamcal/emoji-data") {
  Container(iamcalemojidata.jsdeliverCDN, "jsdeliver CDN", "json", $tags="")[[https://cdn.jsdelivr.net/npm/emoji-datasource-twitter/emoji.json]]
}

Rel_D(Iris, iamcalemojidata.jsdeliverCDN, "Retrieves latest Emoji Data and Images", $tags="")

SHOW_LEGEND()
@enduml
