version: '3.8'

services:

    redis:
        image: redis:alpine
        networks:
            - Iris
        healthcheck:
          test: ["CMD", "redis-cli", "ping"]
          interval: 1s
          timeout: 3s
          retries: 30

    redisinsight:
        image: redislabs/redisinsight:latest
        networks:
            - Iris
        ports:
            - 8091:8001
        depends_on:
            redis:
                condition: service_healthy

    worker:
        image: ${DOCKER_REGISTRY-}worker
        build:
            context: .
            dockerfile: Worker/Dockerfile
        deploy:
            replicas: 2
        depends_on:
            redis:
                condition: service_healthy
        networks:
            - Iris

    ingress:
        image: ${DOCKER_REGISTRY-}ingress
        build:
            context: .
            dockerfile: Ingress/Dockerfile
        depends_on:
            redis:
                condition: service_healthy
        networks:
            - Iris
        environment:
            IRIS_TWITTER_BEARER: "AAAAAAAAAAAAAAAAAAAAAAeUSQEAAAAAARyJIkHJYEXkpQxTuSJjqC%2B7kTI%3D8kiLOfNYaYodoQa4w5LTXMnrFMdLqDr41UtPpAQkHUbx0pc6lp"
            IRIS_TWITTER_ENDPOINT: "/2/tweets/sample/stream"
    
networks:
    Iris:
        name: Iris